// ─── HOOK DE CONTEÚDO TRILÍNGUE ───────────────────────────────────────────────
// Retorna o conteúdo do jogo no idioma selecionado
// PT = content.js original (padrão)
// EN = content_en.js (sobrepõe strings PT)
// ES = content_es.js (sobrepõe strings PT)

import {
  M0_PUZZLE, M1_LESSONS, M1_FINAL_CHALLENGE,
  M2_CHALLENGE, M3_LESSONS, M3_SKIP_CHALLENGE,
  M5_LESSONS, M5_FINAL_CHALLENGE, M6_PUZZLES, M7_LESSONS, M7_FINAL_CHALLENGE, MISSIONS,
} from '../data/content';

// Importações EN
import {
  M0_PUZZLE_EN, M1_LESSONS_EN, M1_FINAL_CHALLENGE_EN,
  M2_CHALLENGE_EN, M3_LESSONS_EN, M3_SKIP_CHALLENGE_EN,
  M5_LESSONS_EN, M5_FINAL_CHALLENGE_EN, M6_PUZZLES_EN, MISSIONS_EN,
} from '../data/content_en';

// Importações ES
import {
  M0_PUZZLE_ES, M1_LESSONS_ES, M1_FINAL_CHALLENGE_ES,
  M2_CHALLENGE_ES, M3_LESSONS_ES, M3_SKIP_CHALLENGE_ES,
  M5_LESSONS_ES, M5_FINAL_CHALLENGE_ES, MISSIONS_ES,
} from '../data/content_es';

const CONTENT = {
  pt: {
    M0_PUZZLE, M1_LESSONS, M1_FINAL_CHALLENGE,
    M2_CHALLENGE, M3_LESSONS, M3_SKIP_CHALLENGE,
    M5_LESSONS, M5_FINAL_CHALLENGE, M6_PUZZLES, M7_LESSONS, M7_FINAL_CHALLENGE, MISSIONS,
  },
  en: {
    M0_PUZZLE: M0_PUZZLE_EN, M1_LESSONS: M1_LESSONS_EN,
    M1_FINAL_CHALLENGE: M1_FINAL_CHALLENGE_EN,
    M2_CHALLENGE: M2_CHALLENGE_EN, M3_LESSONS: M3_LESSONS_EN,
    M3_SKIP_CHALLENGE: M3_SKIP_CHALLENGE_EN,
    M5_LESSONS: M5_LESSONS_EN, M5_FINAL_CHALLENGE: M5_FINAL_CHALLENGE_EN,
    M6_PUZZLES: M6_PUZZLES_EN, MISSIONS: MISSIONS_EN,
  },
  es: {
    M0_PUZZLE: M0_PUZZLE_ES, M1_LESSONS: M1_LESSONS_ES,
    M1_FINAL_CHALLENGE: M1_FINAL_CHALLENGE_ES,
    M2_CHALLENGE: M2_CHALLENGE_ES, M3_LESSONS: M3_LESSONS_ES,
    M3_SKIP_CHALLENGE: M3_SKIP_CHALLENGE_ES,
    M5_LESSONS: M5_LESSONS_ES, M5_FINAL_CHALLENGE: M5_FINAL_CHALLENGE_ES,
    M6_PUZZLES: M6_PUZZLES_EN, MISSIONS: MISSIONS_ES, // reusar EN para M6
  },
};

export function useContent(lang = 'pt') {
  return CONTENT[lang] || CONTENT.pt;
}
